
@baseUrl = http://localhost:3333

GET {{baseUrl}}/ HTTP/1.1
Content-Type: application/json
Accept: application/json

###

GET {{baseUrl}}/status HTTP/1.1
Content-Type: application/json
Accept: application/json
auth: 2re3422e-2e2e-2e2e-2e2e-2e2e2e2e2e2e

###

GET {{baseUrl}}/account HTTP/1.1
Content-Type: application/json
Accept: application/json
auth: 2re3422e-2e2e-2e2e-2e2e-2e2e2e2e2e2e

###

GET {{baseUrl}}/account/12345678910 HTTP/1.1
Content-Type: application/json
Accept: application/json
auth: 2re3422e-2e2e-2e2e-2e2e-2e2e2e2e2e2e

###

POST {{baseUrl}}/account HTTP/1.1
Content-Type: application/json
Accept: application/json
auth: 2re3422e-2e2e-2e2e-2e2e-2e2e2e2e2e2e

{
    "cpf": "12345678910",
    "name": "Cliente Cpf 12345678910"
}

###

GET {{baseUrl}}/statement HTTP/1.1
Content-Type: application/js
Accept: application/json
auth: 2re3422e-2e2e-2e2e-2e2e-2e2e2e2e2e2e
cpf: 12345678910

###

POST {{baseUrl}}/deposit HTTP/1.1
Content-Type: application/json
Accept: application/json
auth: 2re3422e-2e2e-2e2e-2e2e-2e2e2e2e2e2e
cpf: 12345678910

{
    "description" : "Depósito referente a teste de API",
    "amount" : 100.00
}